{'type': 'Block',
 'stmts': [{'type': 'LocalDecl',
            'names': ['Players'],
            'exprs': [{'type': 'MethodCallExpr',
                       'obj': {'type': 'Name', 'name': 'game'},
                       'method': 'GetService',
                       'args': [{'type': 'StringLit', 'value': '"Players"'}]}]},
           {'type': 'LocalDecl',
            'names': ['localPlayer'],
            'exprs': [{'type': 'FieldExpr',
                       'obj': {'type': 'Name', 'name': 'Players'},
                       'field': 'LocalPlayer'}]},
           {'type': 'LocalDecl',
            'names': ['character'],
            'exprs': [{'type': 'BinOp',
                       'op': 'or',
                       'left': {'type': 'FieldExpr',
                                'obj': {'type': 'Name', 'name': 'localPlayer'},
                                'field': 'Character'},
                       'right': {'type': 'MethodCallExpr',
                                 'obj': {'type': 'FieldExpr',
                                         'obj': {'type': 'Name', 'name': 'localPlayer'},
                                         'field': 'CharacterAdded'},
                                 'method': 'Wait',
                                 'args': []}}]},
           {'type': 'LocalDecl',
            'names': ['humanoid'],
            'exprs': [{'type': 'MethodCallExpr',
                       'obj': {'type': 'Name', 'name': 'character'},
                       'method': 'FindFirstChild',
                       'args': [{'type': 'StringLit', 'value': '"Humanoid"'}]}]},
           {'type': 'Assign',
            'targets': [{'type': 'Name', 'name': 'desiredSpeed'}],
            'exprs': [{'type': 'NumberLit', 'value': '64'}]},
           {'type': 'FuncDecl',
            'name': 'applyWalkspeed',
            'params': ['newCharacter'],
            'body': {'type': 'Block',
                     'stmts': [{'type': 'LocalDecl',
                                'names': ['humanoid'],
                                'exprs': [{'type': 'MethodCallExpr',
                                           'obj': {'type': 'Name', 'name': 'newCharacter'},
                                           'method': 'FindFirstChild',
                                           'args': [{'type': 'StringLit',
                                                     'value': '"Humanoid"'}]}]},
                               {'type': 'Assign',
                                'targets': [{'type': 'FieldExpr',
                                             'obj': {'type': 'Name', 'name': 'humanoid'},
                                             'field': 'WalkSpeed'}],
                                'exprs': [{'type': 'Name', 'name': 'desiredSpeed'}]}]},
            'is_local': True,
            'is_method': False},
           {'type': 'Assign',
            'targets': [{'type': 'FieldExpr',
                         'obj': {'type': 'Name', 'name': 'humanoid'},
                         'field': 'WalkSpeed'}],
            'exprs': [{'type': 'Name', 'name': 'desiredSpeed'}]},
           {'type': 'CallStmt',
            'call_expr': {'type': 'MethodCallExpr',
                          'obj': {'type': 'FieldExpr',
                                  'obj': {'type': 'Name', 'name': 'localPlayer'},
                                  'field': 'CharacterAdded'},
                          'method': 'Connect',
                          'args': [{'type': 'Name', 'name': 'applyWalkspeed'}]}}]}